### ISSUE TITLE
Team plugin Causing the search page to be a blank page

### ISSUE THREAD

**Issue by gesonchi** [intelliants/subrion-plugin-team#1]
SBRCMS often fatal BUG

Such as due to a plug-in, it can not be displayed, or the normal use of SBR pages or functions.
SBR team should consider whether the various plug-ins will affect each other and damage, hinder.

Such as new questions:

Team plug-in affect the site search function can not be a normal search, retrieve the request to retrieve the page is blank, can not display any content, is a blank page.

The environment and version of the problem:

Php 5 ~ 7
SBRCMS 4.15
Team plugin 4.1.0 ，2017-04-14

**Comment by vbezruchkin** [comment]
Hi,

Thanks for the report.

You can fix the issue by setting the following var to false:

>    public $coreSearchEnabled = true;

It's in includes/classes/ia.front.team.php file inside your plugin.

The search feature is fixed for 4.2.0 compatible version.
